<?php
error_reporting(E_ALL);
ini_set('display_errors', 1);
header("Access-Control-Allow-Origin: *");
header("Access-Control-Allow-Headers: *");
header("Access-Control-Allow-Methods: *");
// echo "testing";

include 'DbConnect.php';
$objDb = new DbConnect;
$conn = $objDb->connect();

$method = $_SERVER['REQUEST_METHOD'];
switch($method) {

    //SETTING GET REQUEST(LIST USER API)
    case "GET":
        $sql = "SELECT * FROM users";
        $stmt = $conn->prepare($sql);
        $stmt->execute();
        $users = $stmt->fetchAll(PDO::FETCH_ASSOC);
        echo json_encode($users);
        break;

    //SETTING POST REQUEST(CREATE USER API)
    case "POST":
        //The file_get_contents function reads the raw data from the 
        //request body and the json_decode function converts the JSON data into a PHP object. 
        //The decoded data is then stored in the variable $user.
        $user = json_decode(file_get_contents('php://input'));
        //null is 'id' in values because id is generated by auto increment (A_I)
        $sql = "INSERT INTO users(id, name, age, state, role, created_at) VALUES(null, :name, :age, :state, :role, :created_at)";
        $stmt = $conn->prepare($sql);
        $created_at = date('Y-m-d');
        $stmt->bindParam(':name', $user->name);
        $stmt->bindParam(':age', $user->age);
        $stmt->bindParam(':role', $user->role);
        $stmt->bindParam(':state', $user->state);
        $stmt->bindParam(':created_at', $created_at);
        //if else for message $_POST success
        if($stmt->execute()) {
            $response = ['status' => 1, 'message' => 'Record created successfully.'];
        } else {
            $response = ['status' => 0, 'message' => 'Failed to create record.'];
        }
        //echo to print the  $response message in console
        echo json_encode($response);
        break;

    //DELETE REQUEST
    case "DELETE":
        $sql = "DELETE FROM users WHERE id = :id";
        $path = explode('/', $_SERVER['REQUEST_URI']);
        $stmt = $conn->prepare($sql);
        $stmt->bindParam(':id', $path[3]);
        if($stmt->execute()) {
            $response = ['status' => 1, 'message' => 'Record deleted successfully.'];
        } else {
            $response = ['status' => 0, 'message' => 'Failed to delete record.'];
        }
        //echo to print the  $response message in console
        echo json_encode($response);
        break;
}    
